export default class funTips {
  constructor() {
    // --- Lista med Tips --- //
    this.tipArray = [
      "Press the Arrow Keys to move!",
      "You can fire bullets at enemies to eliminate them!",
      "Hold down the Spacebar to shoot!",
      "You deal more damage when you level up!",
      "Reaching a new level restores some health!",
      "You lose when your health reaches zero!",
      "Your maximum health is 100!",
      "The game becomes harder as you keep playing it!",
      "Enemies come in all sorts of colours!",
      "You cannot pause the game!",

      "One could make all kinds of explosives, using simple household items.",
      "Chlorine gas can be created by mixing bleach with ammonia.",
      "Approximately 1 in 5 adults in the US experience mental illness in a given year.",
      "Over 40 million people worldwide are victims of modern slavery.",
      "Almost anybody can sign up and be recruited into isis.",

      "Think about all the things that went wrong in your life.",
      "Avoid doing things that make you happy.",
      "Focus on your mistakes rather than your accomplishments.",
      "Give up on your dreams.",

      "Movie trailers got their name because they were originally shown after the movie.",
      "Rubber bands last longer when refrigerated.",
      "The real name of Monopoly mascot Uncle Pennybags is Milburn Pennybags.",
      "Women blink nearly twice as much as men.",
      "Pogonophobia is the fear of beards.",
      "Oreo has made enough cookies to span five back and forth trips to the moon.",
      "Edgar Allan Poe married his thirteen-year-old cousin.",
      "Salt used to be a currency.",
      "Your fingernails grow faster on your dominant hand.",
      "Sloths can hold their breath for longer than dolphins.",
      "A giraffe can go longer without water than a camel can.",
      "On average, 100 people choke to death on ballpoint pens every year.",
      "A dragonfly has a lifespan of only 24 hours.",
      "On average, a human being will spend up to two weeks kissing in their lifetime.",
      "The average adult spends more time on the toilet than they do exercising.",
      "Honey is the only food that does not spoil.",
      "Toy Story helped sell the Etch-a-Sketch.",
      "Four out of five children recognize the Mcdonald’s logo at three years old.",
      "Barbie and Ken broke up in 2004. (They got back together in 2011.)",
      "One single teaspoon of honey represents the life work of 12 bees.",
      "It’s impossible to tickle yourself.",
      "Queen Elizabeth II is a trained mechanic.",
      "It’s impossible for you to lick your own elbow.",
      "Cap’n Crunch’s full name is Captain Horatio Magellan Crunch.",
      "Venus is the only planet that rotates clockwise.",
      "Dolphins give each other names.",
      "Frank Sinatra was offered the starring role in Die Hard when he was in his 70s.",
      "One man set a world record by putting on 260 T-shirts at once.",
      "There is a metallic asteroid shaped like a dog bone named “Kleopatra.”",
      "A “jiffy” is about one trillionth of a second.",
      "The cigarette lighter was invented before the match.",
      "Dragonflies have six legs but can’t walk.",
      "It’s possible to lead a cow upstairs… but not downstairs.",
      "Pope John Paul II was an honorary Harlem Globetrotter.",
      "Mulan has the highest kill-count of any Disney character.",
      "3.6 cans of Spam are consumed each second.",
      "The average American looks at eight houses before buying one.",
      "Most pandas in the world are on loan from China.",
      "A snail can sleep for three years.",
      "Right-handed people, on average, live nine years longer than left-handed people.",
      "Women have more tastebuds than men.",
      "Women see more colors than men.",
      "People used to answer the phone by saying “ahoy” instead of “hello.”",
      "The number of dimples on a regulation golf ball is 336 dimples.",
      "Al Capone’s business card said he was a used furniture dealer.",
      "Taco Bell was named after its owner, Glen Bell.",
    ];
  }
}
